blank_issues_enabled: false
contact_links:
  - name: New app
    url: https://github.com/EUCPilots/evergreen-apps/issues
    about: For new apps, see the evergreen-apps repository.
  - name: Review known issues
    url: https://eucpilots.com/evergreen-docs/issues
    about: Please ensure you have read the Evergreen known issues list before creating an issue.
  - name: Review troubleshooting
    url: https://eucpilots.com/evergreen-docs/troubleshoot/
    about: Please ensure you have read the Evergreen troubleshooting article before creating an issue.